### ISSUE TITLE
Create ERD (Database)

### ISSUE THREAD

**Issue by renesansz** [DevconDavao/devcon-davao-covid19-tracker-api#4]

**Comment by phillip-atr** [comment]
![image](https://user-images.githubusercontent.com/59261543/87846692-561cc680-c904-11ea-977d-cafb2ce409a1.png)

**Comment by renesansz** [comment]
@phillip-atr I think "Total Cases" shouldn't have a separate table since this can be retrieved with query.

**Comment by phillip-atr** [comment]
Okay. Naa pay lain dungag ani or okay nani as of now?

**Comment by renesansz** [comment]
ang Users/Frontliner tables kulang

**Comment by phillip-atr** [comment]
kana lang kay wala ko kabalo kung unsay exact data ana pero mag buhat nlng ghapon kog ERD ana. just to be sure.

**Comment by renesansz** [comment]
@phillip-atr yep 👍. i include tanan tables na i implement nimo

**Comment by emmandev** [comment]
@phillip-atr @renesansz dili ba bali ang `HOSPITAL_CASES` ang naay `hospital_id`?

**Comment by renesansz** [comment]
@emmandev hm. naa kay point. @phillip-atr can you explain sa imo diagram ngano many-to-one relationship ang `HOSPITALS` & `HOSPITAL_CASES`?

**Comment by emmandev** [comment]
PR is #5. Didto na lang ta review sa mga models.

**Comment by phillip-atr** [comment]
Actually gani, at first naa sa `HOSPITAL_CASES` ang hospital id. Na change guro nako tungod naka plural ang `HOSPITALS`.

**Comment by phillip-atr** [comment]
bali mali nako ni siya. 

and check ang edited sa picture naay history sa una nakong ERD.
